name: 'Send test results to wix bi'
description: 'Custom action used to send test reports for analyses '
author: 'core3'
branding:
  icon: 'crosshair'
  color: 'blue'
inputs:
  testReportFile: 
    required: true
    description: 'input file in json format. mocha json repoter results'
  actionLink: 
    required: true
    description: 'link toi action that executed the tests'
  os: 
    required: false
    description: 'operation system on which test runs'
  node: 
    required: false
    description: 'node version on which test runs'
  
runs:
  using: 'node12'
  main: 'dist/index.js'