name: 'build-test'
on: [pull_request,push ]
jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, widnows-latest, macos-latest]
        node-version: [14,16]
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, widnows-latest, macos-latest]
        node-version: [14,16]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          testReportFile: '__tests__/fixtures/mocha-report.json'
          actionLink: 'dummy/link'
          os: test          
      - uses: ./
        with:
          testReportFile: '__tests__/fixtures/mocha-report-multiple.json'
          actionLink: 'dummy/link'
          os: ${{ matrix.os }}
          node: ${{ matrix.node-version }}
      - uses: ./
        with:
          testReportFile: '__tests__/fixtures/mocha-report-multiple.json,__tests__/fixtures/mocha-report.json'
          actionLink: 'dummy/link'
          os: ${{ matrix.os }}
          node: ${{ matrix.node-version }}
      

